version: '3.5'

services:
  postgres:
    container_name: postgres_container
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: mypass
      POSTGRES_DB: ecommerce
      PGDATA: /data/postgres
    volumes:
       - ./databases/postgres:/data/postgres
    ports:
      - "5432:5432"
    restart: always