server:
  port: 8081

spring:
  application:
    name: auth-ms
  datasource:
    url: jdbc:postgresql://localhost:5432/ecommerce?currentSchema=auth
    username: postgres
    password: mypass
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        default_schema: auth
        format_sql: true
        jdbc:
          lob:
            non_contextual_creation: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
  flyway: # <-- aqui fora de "jpa"
    enabled: true
    schemas: auth
    baseline-on-migrate: true
    baseline-version: "1_001"
    ignore-future-migrations: false
